name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Install TFX
        run: npm install -g tfx-cli
      - name: Build
        run: npm run build
      - name: Package ADO Task
        run: npm run package
      - name: Publish ADO Task
        uses: actions/upload-artifact@v3
        with:
          name: ado-task
          path: Microsoft.microsoft-store-win32-release-task-*.vsix